module.exports = {
    languages: {
        ar: 'Arabic',
        az: 'Azerbaijani',
        be: 'Belarusian',
        bg: 'Bulgarian',
        cs: 'Czech',
        da: 'Danish',
        de: 'German',
        el: 'Greek',
        en: 'English',
        es: 'Spanish',
        et: 'Estonian',
        fi: 'Finnish',
        fr: 'French',
        hi: 'Hindi',
        hr: 'Croatian',
        hu: 'Hungarian',
        id: 'Indonesian',
        it: 'Italian',
        ja: 'Japanese',
        ka: 'Georgian',
        kk: 'Kazakh',
        ko: 'Korean',
        ky: 'Kyrgyz',
        lt: 'Lithuanian',
        lv: 'Latvian',
        mk: 'FYRO Macedonian',
        ms: 'Malay',
        nl: 'Dutch',
        no: 'Norwegian',
        pl: 'Polish',
        pt: 'Portuguese',
        ro: 'Romanian',
        ru: 'Russian',
        sk: 'Slovak',
        sl: 'Slovenian',
        sq: 'Albanian',
        sr: 'Serbian',
        sw: 'Swahili',
        th: 'Thai',
        tr: 'Turkish',
        uk: 'Ukrainian',
        uz: 'Uzbek',
        vi: 'Vietnamese',
        'zh-CN': 'Chinese (Simplified)',
        'zh-TW': 'Chinese (Traditional)'
    },
    translations: [
        { category: 'app', type: 'source', patterns: ['src/**/!(*-cli).js', 'src/**/*.vue', 'src/**/*.html'] },
        { category: 'calendar', type: 'source', patterns: ['src/components/Calendar.vue'] },
        {
            category: 'object-form',
            type: 'source',
            patterns: ['src/components/ObjectForm.vue', 'src/components/ObjectFormField.vue']
        }
    ]
}
